# Apple Metal support for pytorch GPU programming 

https://developer.apple.com/metal/pytorch/

In [1]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [2]:
from torch import tensor 

In [9]:
x = tensor([range(1000), range(1000,2000)])
x

tensor([[   0,    1,    2,  ...,  997,  998,  999],
        [1000, 1001, 1002,  ..., 1997, 1998, 1999]])

In [10]:
x.shape

torch.Size([2, 1000])

In [13]:
x = x.to("mps")

In [14]:
x

tensor([[   0,    1,    2,  ...,  997,  998,  999],
        [1000, 1001, 1002,  ..., 1997, 1998, 1999]], device='mps:0')